In [2]:
# 파이썬에서 sql에 연동할 수 있는 라이브러리 설치
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\ezen\appdata\local\programs\python\python311\lib\site-packages (1.1.0)

In [3]:
import pymysql

# mysql 연동
1. DB 서버와의 연결
    - 서버의 주소
    - 아이디
    - 비밀번호
    - Database
    - Port
2. Cursor를 생성(sql과 python을 연결해주는 가상의 임시 공간이라고 생각하세요)
    - sql 서버와 python 사이에 있는 가상의 공간     
3. sql 쿼리문을 작성
4. Cursor를 이용하여 sql쿼리문을 sql 서버에 보내준다. (execute)
5. Select문 경우에는 결과값을 Cursor에서 받아온다.
6. insert, update, delete문의 경우에는 데이터가 수정되므로 sql서버에 데이터를 변경 (commit)
7. sql 서버와의 연결을 종료

In [4]:
# 서버와의 연결
_db = pymysql.connect(
    host = '127.0.0.1', #localhost라고 적어도 됨. 저 IP주소는 언제나 내가 쓰고 있는 컴퓨터를 뜻함.
    user = 'root',
    password = '1234',
    database = 'ezen',
    port = 3306 #가장 기본적인 포트번호는 3306이다.
)

In [6]:
# Cursor 생성
# cursor() : 인자값을 넣지 않으면 결과값을 받아올 때 tuple의 형태로 데이터를 가져온다.
# 근데 우리는 데이터분석을 할 거라서 일반적으로 딕셔너리 형태로 받아옵니당(DictCursor의 뜻이얌) & 괄호 안에 인자값을 넣는거죵.
cursor = _db.cursor(pymysql.cursors.DictCursor) #DictCursor 대소문자 구분

In [7]:
# 테이블을 생성하는 sql 쿼리문을 작성
sql = """
    create
    table
    user(
        id varchar(32) primary key,
        password varchar(32) not null,
        name varchar(32) not null,
        gender int
    );
"""
# cursor에 있는 execute()함수를 이용하여 쿼리문을 실행
cursor.execute(sql)

0

In [9]:
# insert문을 이용하여 데이터를 삽입
# 두 번 실행하면 error남. 첫번째 실행에서 이미 값들이 들어갔으므로
# 여기까지만 하면 실제 데이터베이스에는 들어가지 않음. cursor공간에만 있을뿐.
# 이후 과정으로 commit()을 써야 함.
sql = """
    insert
    into
    user(
        id,
        password,
        name
    )
    values
    (
        'test', 
        '1234', 
        'kim'
    )
"""

cursor.execute(sql)

1

In [10]:
_db.commit()

In [37]:
# 외부의 데이터베이스 서버에 접속(선생님 개인 컴터)

_db2 = pymysql.connect(
    host = 'darkpreist.iptime.org',
    user = 'ubion',
    password = '1234',
    database = 'ubion',
    port = 3306
)

In [38]:
cursor = _db2.cursor(pymysql.cursors.DictCursor)
#위에서 cursor 썼는데, cursor 걍 덮어씌웠음. 참고햐

In [39]:
sql = """
    SELECT #일반적으로 쿼리문은 대문자로 씁니다.
    *
    FROM
    `sales records` #숫자키1 옆에 있는 특수문자. 백쿼트는 띄어쓰기가 있을 때 묶는 용도임.
"""

cursor.execute(sql)

#결과가 10000이 나올텐데, 이 10000의 뜻은 데이터가 10000개라는 뜻이다.

10000

In [40]:
# cursor 공간에서 데이터를 불러온다.
data = cursor.fetchall()

In [41]:
data

[{'Region': 'Sub-Saharan Africa',
  'Country': 'Chad',
  'Item Type': 'Office Supplies',
  'Sales Channel': 'Online',
  'Order Priority': 'L',
  'Order Date': '1/27/2011',
  'Order ID': 292494523,
  'Ship Date': '2/12/2011',
  'Units Sold': 4484,
  'Unit Price': 651.21,
  'Unit Cost': 524.96,
  'Total Revenue': 2920025.64,
  'Total Cost': 2353920.64,
  'Total Profit': 566105.0},
 {'Region': 'Europe',
  'Country': 'Latvia',
  'Item Type': 'Beverages',
  'Sales Channel': 'Online',
  'Order Priority': 'C',
  'Order Date': '12/28/2015',
  'Order ID': 361825549,
  'Ship Date': '1/23/2016',
  'Units Sold': 1075,
  'Unit Price': 47.45,
  'Unit Cost': 31.79,
  'Total Revenue': 51008.75,
  'Total Cost': 34174.25,
  'Total Profit': 16834.5},
 {'Region': 'Middle East and North Africa',
  'Country': 'Pakistan',
  'Item Type': 'Vegetables',
  'Sales Channel': 'Offline',
  'Order Priority': 'C',
  'Order Date': '1/13/2011',
  'Order ID': 141515767,
  'Ship Date': '2/1/2011',
  'Units Sold': 6515,
  'Unit Price': 154.06,
  'Unit Cost': 90.93,
  'Total Revenue': 1003700.9,
  'Total Cost': 592408.95,
  'Total Profit': 411291.95},
 {'Region': 'Sub-Saharan Africa',
  'Country': 'Democratic Republic of the Congo',
  'Item Type': 'Household',
  'Sales Channel': 'Online',
  'Order Priority': 'C',
  'Order Date': '9/11/2012',
  'Order ID': 500364005,
  'Ship Date': '10/6/2012',
  'Units Sold': 7683,
  'Unit Price': 668.27,
  'Unit Cost': 502.54,
  'Total Revenue': 5134318.41,
  'Total Cost': 3861014.82,
  'Total Profit': 1273303.59},
 {'Region': 'Europe',
  'Country': 'Czech Republic',
  'Item Type': 'Beverages',
  'Sales Channel': 'Online',
  'Order Priority': 'C',
  'Order Date': '10/27/2015',
  'Order ID': 127481591,
  'Ship Date': '12/5/2015',
  'Units Sold': 3491,
  'Unit Price': 47.45,
  'Unit Cost': 31.79,
  'Total Revenue': 165647.95,
  'Total Cost': 110978.89,
  'Total Profit': 54669.06},
 {'Region': 'Sub-Saharan Africa',
  'Country': 'South Africa',
  'Item Type': 'Beverages',
  'Sales Channel': 'Offline',
  'Order Priority': 'H',
  'Order Date': '7/10/2012',
  'Order ID': 482292354,
  'Ship Date': '8/21/2012',
  'Units Sold': 9880,
  'Unit Price': 47.45,
  'Unit Cost': 31.79,
  'Total Revenue': 468806.0,
  'Total Cost': 314085.2,
  'Total Profit': 154720.8},
 {'Region': 'Asia',
  'Country': 'Laos',
  'Item Type': 'Vegetables',
  'Sales Channel': 'Online',
  'Order Priority': 'L',
  'Order Date': '2/20/2011',
  'Order ID': 844532620,
  'Ship Date': '3/20/2011',
  'Units Sold': 4825,
  'Unit Price': 154.06,
  'Unit Cost': 90.93,
  'Total Revenue': 743339.5,
  'Total Cost': 438737.25,
  'Total Profit': 304602.25},
 {'Region': 'Asia',
  'Country': 'China',
  'Item Type': 'Baby Food',
  'Sales Channel': 'Online',
  'Order Priority': 'C',
  'Order Date': '4/10/2017',
  'Order ID': 564251220,
  'Ship Date': '5/12/2017',
  'Units Sold': 3330,
  'Unit Price': 255.28,
  'Unit Cost': 159.42,
  'Total Revenue': 850082.4,
  'Total Cost': 530868.6,
  'Total Profit': 319213.8},
 {'Region': 'Sub-Saharan Africa',
  'Country': 'Eritrea',
  'Item Type': 'Meat',
  'Sales Channel': 'Online',
  'Order Priority': 'L',
  'Order Date': '11/21/2014',
  'Order ID': 411809480,
  'Ship Date': '1/10/2015',
  'Units Sold': 2431,
  'Unit Price': 421.89,
  'Unit Cost': 364.69,
  'Total Revenue': 1025614.59,
  'Total Cost': 886561.39,
  'Total Profit': 139053.2},
 {'Region': 'Central America and the Caribbean',
  'Country': 'Haiti',
  'Item Type': 'Office Supplies',
  'Sales Channel': 'Online',
  'Order Priority': 'C',
  'Order Date': '7/4/2015',
  'Order ID': 327881228,
  'Ship Date': '7/20/2015',
  'Units Sold': 6197,
  'Unit Price': 651.21,
  'Unit Cost': 524.96,
  'Total Revenue': 4035548.37,
  'Total Cost': 3253177.12,
  'Total Profit': 782371.25},
 {'Region': 'Sub-Saharan Africa',
  'Country': 'Zambia',
  'Item Type': 'Cereal',
  'Sales Channel': 'Offline',
  'Order Priority': 'M',
  'Order Date': '7/26/2016',
  'Order ID': 773452794,
  'Ship Date': '8/24/2016',
  'Units Sold': 724,
  'Unit Price': 205.7,
  'Unit Cost': 117.11,
  'Total Revenue': 148926.8,
  'Total Cost': 84787.64,
  'Total Profit': 64139.16},
 {'Region': 'Europe',
  'Country': 'Bosnia and Herzegovina',
  'Item Type': 'Baby Food',
  'Sales Channel': 'Offline',
  'Order Priority': 'M',
  'Order Date': '10/20/2012',
  'Order ID': 479823005,
  'Ship Date': '11/15/2012',
  'Units Sold': 9145,
  'Unit Price': 255.28,
  'Unit Cost': 159.42,
  'Total Revenue': 2334535.6,
  'Total Cost': 1457895.9,
  'Total Profit': 876639.7},
 {'Region': 'Europe',
  'Country': 'Germany',
  'Item Type': 'Office Supplies',
  'Sales Channel': 'Online',
  'Order Priority': 'C',
  'Order Date': '2/22/2015',
  'Order ID': 498603188,
  'Ship Date': '2/27/2015',
  'Units Sold': 6618,
  'Unit Price': 651.21,
  'Unit Cost': 524.96,
  'Total Revenue': 4309707.78,
  'Total Cost': 3474185.28,
  'Total Profit': 835522.5},
 {'Region': 'Asia',
  'Country': 'India',
  'Item Type': 'Household',
  'Sales Channel': 'Online',
  'Order Priority': 'C',
  'Order Date': '8/27/2016',
  'Order ID': 151717174,
  'Ship Date': '9/2/2016',
  'Units Sold': 5338,
  'Unit Price': 668.27,
  'Unit Cost': 502.54,
  'Total Revenue': 3567225.26,
  'Total Cost': 2682558.52,
  'Total Profit': 884666.74},
 {'Region': 'Middle East and North Africa',
  'Country': 'Algeria',
  'Item Type': 'Clothes',
  'Sales Channel': 'Offline',
  'Order Priority': 'C',
  'Order Date': '6/21/2011',
  'Order ID': 181401288,
  'Ship Date': '7/21/2011',
  'Units Sold': 9527,
  'Unit Price': 109.28,
  'Unit Cost': 35.84,
  'Total Revenue': 1041110.56,
  'Total Cost': 341447.68,
  'Total Profit': 699662.88},
 {'Region': 'Australia and Oceania',
  'Country': 'Palau',
  'Item Type': 'Snacks',
  'Sales Channel': 'Offline',
  'Order Priority': 'L',
  'Order Date': '9/19/2013',
  'Order ID': 500204360,
  'Ship Date': '10/4/2013',
  'Units Sold': 441,
  'Unit Price': 152.58,
  'Unit Cost': 97.44,
  'Total Revenue': 67287.78,
  'Total Cost': 42971.04,
  'Total Profit': 24316.74},
 {'Region': 'Central America and the Caribbean',
  'Country': 'Cuba',
  'Item Type': 'Beverages',
  'Sales Channel': 'Online',
  'Order Priority': 'H',
  'Order Date': '11/15/2015',
  'Order ID': 640987718,
  'Ship Date': '11/30/2015',
  'Units Sold': 1365,
  'Unit Price': 47.45,
  'Unit Cost': 31.79,
  'Total Revenue': 64769.25,
  'Total Cost': 43393.35,
  'Total Profit': 21375.9},
 {'Region': 'Europe',
  'Country': 'Vatican City',
  'Item Type': 'Beverages',
  'Sales Channel': 'Online',
  'Order Priority': 'L',
  'Order Date': '4/6/2015',
  'Order ID': 206925189,
  'Ship Date': '4/27/2015',
  'Units Sold': 2617,
  'Unit Price': 47.45,
  'Unit Cost': 31.79,
  'Total Revenue': 124176.65,
  'Total Cost': 83194.43,
  'Total Profit': 40982.22},
 {'Region': 'Middle East and North Africa',
  'Country': 'Lebanon',
  'Item Type': 'Personal Care',
  'Sales Channel': 'Offline',
  'Order Priority': 'H',
  'Order Date': '4/12/2010',
  'Order ID': 221503102,
  'Ship Date': '5/19/2010',
  'Units Sold': 6545,
  'Unit Price': 81.73,
  'Unit Cost': 56.67,
  'Total Revenue': 534922.85,
  'Total Cost': 370905.15,
  'Total Profit': 164017.7},
 {'Region': 'Europe',
  'Country': 'Lithuania',
  'Item Type': 'Snacks',
  'Sales Channel': 'Offline',
  'Order Priority': 'H',
  'Order Date': '9/26/2011',
  'Order ID': 878520286,
  'Ship Date': '10/2/2011',
  'Units Sold': 2530,
  'Unit Price': 152.58,
  'Unit Cost': 97.44,
  'Total Revenue': 386027.4,
  'Total Cost': 246523.2,
  'Total Profit': 139504.2},
 {'Region': 'Sub-Saharan Africa',
  'Country': 'Mauritius ',
  'Item Type': 'Cosmetics',
  'Sales Channel': 'Offline',
  'Order Priority': 'H',
  'Order Date': '5/14/2016',
  'Order ID': 192088067,
  'Ship Date': '6/18/2016',
  'Units Sold': 1983,
  'Unit Price': 437.2,
  'Unit Cost': 263.33,
  'Total Revenue': 866967.6,
  'Total Cost': 522183.39,
  'Total Profit': 344784.21},
 {'Region': 'Europe',
  'Country': 'Ukraine',
  'Item Type': 'Office Supplies',
  'Sales Channel': 'Online',
  'Order Priority': 'C',
  'Order Date': '8/14/2010',
  'Order ID': 746630275,
  'Ship Date': '8/31/2010',
  'Units Sold': 3345,
  'Unit Price': 651.21,
  'Unit Cost': 524.96,
  'Total Revenue': 2178297.45,
  'Total Cost': 1755991.2,
  'Total Profit': 422306.25},
 {'Region': 'Europe',
  'Country': 'Russia',
  'Item Type': 'Snacks',
  'Sales Channel': 'Offline',
  'Order Priority': 'L',
  'Order Date': '4/13/2012',
  'Order ID': 246883237,
  'Ship Date': '4/22/2012',
  'Units Sold': 7091,
  'Unit Price': 152.58,
  'Unit Cost': 97.44,
  'Total Revenue': 1081944.78,
  'Total Cost': 690947.04,
  'Total Profit': 390997.74},
 {'Region': 'Asia',
  'Country': 'Japan',
  'Item Type': 'Cosmetics',
  'Sales Channel': 'Offline',
  'Order Priority': 'H',
  'Order Date': '9/19/2013',
  'Order ID': 967895781,
  'Ship Date': '9/28/2013',
  'Units Sold': 725,
  'Unit Price': 437.2,
  'Unit Cost': 263.33,
  'Total Revenue': 316970.0,
  'Total Cost': 190914.25,
  'Total Profit': 126055.75},
 {'Region': 'Europe',
  'Country': 'Russia',
  'Item Type': 'Meat',
  'Sales Channel': 'Offline',
  'Order Priority': 'L',
  'Order Date': '12/2/2015',
  'Order ID': 305029237,
  'Ship Date': '12/26/2015',
  'Units Sold': 3784,
  'Unit Price': 421.89,
  'Unit Cost': 364.69,
  'Total Revenue': 1596431.76,
  'Total Cost': 1379986.96,
  'Total Profit': 216444.8},
 {'Region': 'Europe',
  'Country': 'Liechtenstein',
  'Item Type': 'Vegetables',
  'Sales Channel': 'Offline',
  'Order Priority': 'L',
  'Order Date': '2/26/2017',
  'Order ID': 223957431,
  'Ship Date': '2/28/2017',
  'Units Sold': 2835,
  'Unit Price': 154.06,
  'Unit Cost': 90.93,
  'Total Revenue': 436760.1,
  'Total Cost': 257786.55,
  'Total Profit': 178973.55},
 {'Region': 'Europe',
  'Country': 'Greece',
  'Item Type': 'Clothes',
  'Sales Channel': 'Online',
  'Order Priority': 'C',
  'Order Date': '10/9/2016',
  'Order ID': 510666692,
  'Ship Date': '10/13/2016',
  'Units Sold': 6477,
  'Unit Price': 109.28,
  'Unit Cost': 35.84,
  'Total Revenue': 707806.56,
  'Total Cost': 232135.68,
  'Total Profit': 475670.88},
 {'Region': 'Europe',
  'Country': 'Albania',
  'Item Type': 'Baby Food',
  'Sales Channel': 'Offline',
  'Order Priority': 'C',
  'Order Date': '5/20/2011',
  'Order ID': 121455848,
  'Ship Date': '6/19/2011',
  'Units Sold': 339,
  'Unit Price': 255.28,
  'Unit Cost': 159.42,
  'Total Revenue': 86539.92,
  'Total Cost': 54043.38,
  'Total Profit': 32496.54},
 {'Region': 'Australia and Oceania',
  'Country': 'Federated States of Micronesia',
  'Item Type': 'Baby Food',
  'Sales Channel': 'Online',
  'Order Priority': 'M',
  'Order Date': '10/24/2013',
  'Order ID': 332936227,
  'Ship Date': '12/3/2013',
  'Units Sold': 2083,
  'Unit Price': 255.28,
  'Unit Cost': 159.42,
  'Total Revenue': 531748.24,
  'Total Cost': 332071.86,
  'Total Profit': 199676.38},
 {'Region': 'Central America and the Caribbean',
  'Country': 'Dominica',
  'Item Type': 'Beverages',
  'Sales Channel': 'Offline',
  'Order Priority': 'H',
  'Order Date': '6/14/2011',
  'Order ID': 692031657,
  'Ship Date': '7/20/2011',
  'Units Sold': 6401,
  'Unit Price': 47.45,
  'Unit Cost': 31.79,
  'Total Revenue': 303727.45,
  'Total Cost': 203487.79,
  'Total Profit': 100239.66},
 {'Region': 'Europe',
  'Country': 'Andorra',
  'Item Type': 'Office Supplies',
  'Sales Channel': 'Online',
  'Order Priority': 'M',
  'Order Date': '6/20/2015',
  'Order ID': 365978467,
  'Ship Date': '7/21/2015',
  'Units Sold': 16,
  'Unit Price': 651.21,
  'Unit Cost': 524.96,
  'Total Revenue': 10419.36,
  'Total Cost': 8399.36,
  'Total Profit': 2020.0},
 {'Region': 'Europe',
  'Country': 'Switzerland',
  'Item Type': 'Personal Care',
  'Sales Channel': 'Online',
  'Order Priority': 'M',
  'Order Date': '8/5/2011',
  'Order ID': 392325484,
  'Ship Date': '9/1/2011',
  'Units Sold': 6684,
  'Unit Price': 81.73,
  'Unit Cost': 56.67,
  'Total Revenue': 546283.32,
  'Total Cost': 378782.28,
  'Total Profit': 167501.04},
 {'Region': 'Central America and the Caribbean',
  'Country': 'Trinidad and Tobago',
  'Item Type': 'Baby Food',
  'Sales Channel': 'Offline',
  'Order Priority': 'L',
  'Order Date': '11/30/2016',
  'Order ID': 528934037,
  'Ship Date': '1/9/2017',
  'Units Sold': 2191,
  'Unit Price': 255.28,
  'Unit Cost': 159.42,
  'Total Revenue': 559318.48,
  'Total Cost': 349289.22,
  'Total Profit': 210029.26},
 {'Region': 'Europe',
  'Country': 'San Marino',
  'Item Type': 'Vegetables',
  'Sales Channel': 'Online',
  'Order Priority': 'H',
  'Order Date': '7/5/2015',
  'Order ID': 603977954,
  'Ship Date': '7/29/2015',
  'Units Sold': 9353,
  'Unit Price': 154.06,
  'Unit Cost': 90.93,
  'Total Revenue': 1440923.18,
  'Total Cost': 850468.29,
  'Total Profit': 590454.89},
 {'Region': 'Central America and the Caribbean',
  'Country': 'Nicaragua',
  'Item Type': 'Fruits',
  'Sales Channel': 'Online',
  'Order Priority': 'L',
  'Order Date': '3/25/2015',
  'Order ID': 965943562,
  'Ship Date': '5/9/2015',
  'Units Sold': 3020,
  'Unit Price': 9.33,
  'Unit Cost': 6.92,
  'Total Revenue': 28176.6,
  'Total Cost': 20898.4,
  'Total Profit': 7278.2},
 {'Region': 'Middle East and North Africa',
  'Country': 'Azerbaijan',
  'Item Type': 'Cosmetics',
  'Sales Channel': 'Online',
  'Order Priority': 'M',
  'Order Date': '8/22/2013',
  'Order ID': 233629691,
  'Ship Date': '8/30/2013',
  'Units Sold': 5072,
  'Unit Price': 437.2,
  'Unit Cost': 263.33,
  'Total Revenue': 2217478.4,
  'Total Cost': 1335609.76,
  'Total Profit': 881868.64},
 {'Region': 'Asia',
  'Country': 'Bangladesh',
  'Item Type': 'Personal Care',
  'Sales Channel': 'Online',
  'Order Priority': 'L',
  'Order Date': '12/11/2016',
  'Order ID': 246147668,
  'Ship Date': '1/13/2017',
  'Units Sold': 9420,
  'Unit Price': 81.73,
  'Unit Cost': 56.67,
  'Total Revenue': 769896.6,
  'Total Cost': 533831.4,
  'Total Profit': 236065.2},
 {'Region': 'Europe',
  'Country': 'Serbia',
  'Item Type': 'Beverages',
  'Sales Channel': 'Online',
  'Order Priority': 'H',
  'Order Date': '6/23/2013',
  'Order ID': 212921321,
  'Ship Date': '7/18/2013',
  'Units Sold': 7005,
  'Unit Price': 47.45,
  'Unit Cost': 31.79,
  'Total Revenue': 332387.25,
  'Total Cost': 222688.95,
  'Total Profit': 109698.3},
 {'Region': 'Sub-Saharan Africa',
  'Country': 'Mauritius ',
  'Item Type': 'Fruits',
  'Sales Channel': 'Offline',
  'Order Priority': 'H',
  'Order Date': '5/8/2015',
  'Order ID': 763686978,
  'Ship Date': '5/13/2015',
  'Units Sold': 803,
  'Unit Price': 9.33,
  'Unit Cost': 6.92,
  'Total Revenue': 7491.99,
  'Total Cost': 5556.76,
  'Total Profit': 1935.23},
 {'Region': 'Central America and the Caribbean',
  'Country': 'Jamaica',
  'Item Type': 'Baby Food',
  'Sales Channel': 'Offline',
  'Order Priority': 'H',
  'Order Date': '10/24/2016',
  'Order ID': 798493468,
  'Ship Date': '11/24/2016',
  'Units Sold': 816,
  'Unit Price': 255.28,
  'Unit Cost': 159.42,
  'Total Revenue': 208308.48,
  'Total Cost': 130086.72,
  'Total Profit': 78221.76},
 {'Region': 'Europe',
  'Country': 'Italy',
  'Item Type': 'Cereal',
  'Sales Channel': 'Offline',
  'Order Priority': 'H',
  'Order Date': '3/10/2013',
  'Order ID': 637702119,
  'Ship Date': '4/4/2013',
  'Units Sold': 9083,
  'Unit Price': 205.7,
  'Unit Cost': 117.11,
  'Total Revenue': 1868373.1,
  'Total Cost': 1063710.13,
  'Total Profit': 804662.97},
 {'Region': 'Asia',
  'Country': 'Bhutan',
  'Item Type': 'Clothes',
  'Sales Channel': 'Offline',
  'Order Priority': 'L',
  'Order Date': '3/18/2012',
  'Order ID': 671986758,
  'Ship Date': '5/4/2012',
  'Units Sold': 4670,
  'Unit Price': 109.28,
  'Unit Cost': 35.84,
  'Total Revenue': 510337.6,
  'Total Cost': 167372.8,
  'Total Profit': 342964.8},
 {'Region': 'Middle East and North Africa',
  'Country': 'Turkey',
  'Item Type': 'Clothes',
  'Sales Channel': 'Online',
  'Order Priority': 'L',
  'Order Date': '2/11/2015',
  'Order ID': 912333714,
  'Ship Date': '3/2/2015',
  'Units Sold': 8675,
  'Unit Price': 109.28,
  'Unit Cost': 35.84,
  'Total Revenue': 948004.0,
  'Total Cost': 310912.0,
  'Total Profit': 637092.0},
 {'Region': 'Europe',
  'Country': 'Bulgaria',
  'Item Type': 'Cosmetics',
  'Sales Channel': 'Offline',
  'Order Priority': 'L',
  'Order Date': '10/30/2012',
  'Order ID': 540041816,
  'Ship Date': '11/3/2012',
  'Units Sold': 9229,
  'Unit Price': 437.2,
  'Unit Cost': 263.33,
  'Total Revenue': 4034918.8,
  'Total Cost': 2430272.57,
  'Total Profit': 1604646.23},
 {'Region': 'Middle East and North Africa',
  'Country': 'Pakistan',
  'Item Type': 'Household',
  'Sales Channel': 'Offline',
  'Order Priority': 'M',
  'Order Date': '7/6/2012',
  'Order ID': 156722390,
  'Ship Date': '8/1/2012',
  'Units Sold': 6493,
  'Unit Price': 668.27,
  'Unit Cost': 502.54,
  'Total Revenue': 4339077.11,
  'Total Cost': 3262992.22,
  'Total Profit': 1076084.89},
 {'Region': 'Europe',
  'Country': 'Poland',
  'Item Type': 'Cereal',
  'Sales Channel': 'Offline',
  'Order Priority': 'C',
  'Order Date': '1/4/2011',
  'Order ID': 434299266,
  'Ship Date': '2/21/2011',
  'Units Sold': 7659,
  'Unit Price': 205.7,
  'Unit Cost': 117.11,
  'Total Revenue': 1575456.3,
  'Total Cost': 896945.49,
  'Total Profit': 678510.81},
 {'Region': 'Europe',
  'Country': 'France',
  'Item Type': 'Baby Food',
  'Sales Channel': 'Offline',
  'Order Priority': 'M',
  'Order Date': '10/25/2013',
  'Order ID': 765008771,
  'Ship Date': '12/10/2013',
  'Units Sold': 1950,
  'Unit Price': 255.28,
  'Unit Cost': 159.42,
  'Total Revenue': 497796.0,
  'Total Cost': 310869.0,
  'Total Profit': 186927.0},
 {'Region': 'Central America and the Caribbean',
  'Country': 'Jamaica',
  'Item Type': 'Baby Food',
  'Sales Channel': 'Offline',
  'Order Priority': 'C',
  'Order Date': '2/16/2016',
  'Order ID': 611399734,
  'Ship Date': '3/22/2016',
  'Units Sold': 5623,
  'Unit Price': 255.28,
  'Unit Cost': 159.42,
  'Total Revenue': 1435439.44,
  'Total Cost': 896418.66,
  'Total Profit': 539020.78},
 {'Region': 'Australia and Oceania',
  'Country': 'Australia',
  'Item Type': 'Personal Care',
  'Sales Channel': 'Online',
  'Order Priority': 'H',
  'Order Date': '3/16/2014',
  'Order ID': 856333482,
  'Ship Date': '4/27/2014',
  'Units Sold': 6962,
  'Unit Price': 81.73,
  'Unit Cost': 56.67,
  'Total Revenue': 569004.26,
  'Total Cost': 394536.54,
  'Total Profit': 174467.72},
 {'Region': 'Middle East and North Africa',
  'Country': 'Somalia',
  'Item Type': 'Fruits',
  'Sales Channel': 'Offline',
  'Order Priority': 'C',
  'Order Date': '9/24/2016',
  'Order ID': 652983844,
  'Ship Date': '10/29/2016',
  'Units Sold': 1285,
  'Unit Price': 9.33,
  'Unit Cost': 6.92,
  'Total Revenue': 11989.05,
  'Total Cost': 8892.2,
  'Total Profit': 3096.85},
 {'Region': 'Europe',
  'Country': 'Slovenia',
  'Item Type': 'Cosmetics',
  'Sales Channel': 'Online',
  'Order Priority': 'M',
  'Order Date': '9/30/2010',
  'Order ID': 574837148,
  'Ship Date': '11/11/2010',
  'Units Sold': 5941,
  'Unit Price': 437.2,
  'Unit Cost': 263.33,
  'Total Revenue': 2597405.2,
  'Total Cost': 1564443.53,
  'Total Profit': 1032961.67},
 {'Region': 'Australia and Oceania',
  'Country': 'Samoa ',
  'Item Type': 'Clothes',
  'Sales Channel': 'Offline',
  'Order Priority': 'C',
  'Order Date': '11/5/2010',
  'Order ID': 365692222,
  'Ship Date': '12/5/2010',
  'Units Sold': 5310,
  'Unit Price': 109.28,
  'Unit Cost': 35.84,
  'Total Revenue': 580276.8,
  'Total Cost': 190310.4,
  'Total Profit': 389966.4},
 {'Region': 'Sub-Saharan Africa',
  'Country': 'South Africa',
  'Item Type': 'Cereal',
  'Sales Channel': 'Online',
  'Order Priority': 'M',
  'Order Date': '7/21/2017',
  'Order ID': 289660394,
  'Ship Date': '8/22/2017',
  'Units Sold': 5802,
  'Unit Price': 205.7,
  'Unit Cost': 117.11,
  'Total Revenue': 1193471.4,
  'Total Cost': 679472.22,
  'Total Profit': 513999.18},
 {'Region': 'Sub-Saharan Africa',
  'Country': 'Ghana',
  'Item Type': 'Vegetables',

In [42]:
#해당하는 데이터를 판다스를 이용해서 데이터프레임 안에 데이터를 넣을거얌.
import pandas as pd

In [43]:
df = pd.DataFrame(data)
df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,1/27/2011,292494523,2/12/2011,4484,651.21,524.96,2920025.64,2353920.64,566105.00
1,Europe,Latvia,Beverages,Online,C,12/28/2015,361825549,1/23/2016,1075,47.45,31.79,51008.75,34174.25,16834.50
2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,1/13/2011,141515767,2/1/2011,6515,154.06,90.93,1003700.90,592408.95,411291.95
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,9/11/2012,500364005,10/6/2012,7683,668.27,502.54,5134318.41,3861014.82,1273303.59
4,Europe,Czech Republic,Beverages,Online,C,10/27/2015,127481591,12/5/2015,3491,47.45,31.79,165647.95,110978.89,54669.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Asia,Laos,Beverages,Online,H,7/15/2014,199342048,7/31/2014,8597,47.45,31.79,407927.65,273298.63,134629.02
9996,Europe,Liechtenstein,Cosmetics,Online,C,10/27/2012,763044106,11/1/2012,562,437.20,263.33,245706.40,147991.46,97714.94
9997,Sub-Saharan Africa,Democratic Republic of the Congo,Vegetables,Offline,M,2/14/2013,848579967,3/20/2013,2524,154.06,90.93,388847.44,229507.32,159340.12
9998,Sub-Saharan Africa,South Africa,Meat,Online,L,2/19/2017,298185956,2/22/2017,8706,421.89,364.69,3672974.34,3174991.14,497983.20
9999,Asia,Mongolia,Snacks,Offline,M,4/12/2016,824410903,4/16/2016,361,152.58,97.44,55081.38,35175.84,19905.54

In [44]:
# 우리가 원하는 colomns 부분만 가져와볼까요?
sql = """
    SELECT
    `Region`,
    `Country`,
    `Sales Channel`,
    `Units Sold`,
    `Unit Cost`,
    `Unit Price`
    FROM
    `sales records`
"""

cursor.execute(sql)

#결과가 10000이 나올텐데, 이 10000의 뜻은 데이터가 10000개라는 뜻이다.

10000

In [45]:
data = cursor.fetchall()

In [46]:
import pandas as pd

In [47]:
df = pd.DataFrame(data)
df

,Region,Country,Sales Channel,Units Sold,Unit Cost,Unit Price
0,Sub-Saharan Africa,Chad,Online,4484,524.96,651.21
1,Europe,Latvia,Online,1075,31.79,47.45
2,Middle East and North Africa,Pakistan,Offline,6515,90.93,154.06
3,Sub-Saharan Africa,Democratic Republic of the Congo,Online,7683,502.54,668.27
4,Europe,Czech Republic,Online,3491,31.79,47.45
...,...,...,...,...,...,...
9995,Asia,Laos,Online,8597,31.79,47.45
9996,Europe,Liechtenstein,Online,562,263.33,437.20
9997,Sub-Saharan Africa,Democratic Republic of the Congo,Offline,2524,90.93,154.06
9998,Sub-Saharan Africa,South Africa,Online,8706,364.69,421.89
9999,Asia,Mongolia,Offline,361,97.44,152.58

In [48]:
# 우리가 원하는 columns 부분만 가져오면서, columns의 이름을 바꿔봅시다.
sql = """
    SELECT
    `Region` as '대륙',
    `Country` as '국가',
    `Sales Channel` as '채널',
    `Units Sold` as '개수',
    `Unit Cost` as '원가',
    `Unit Price` as '단가' #table의 이름이나 columns의 이름은 ``로 묶어줍니다.
    FROM
    `sales records`
"""

cursor.execute(sql)

10000

In [49]:
data = cursor.fetchall()
df = pd.DataFrame(data)
df

,대륙,국가,채널,개수,원가,단가
0,Sub-Saharan Africa,Chad,Online,4484,524.96,651.21
1,Europe,Latvia,Online,1075,31.79,47.45
2,Middle East and North Africa,Pakistan,Offline,6515,90.93,154.06
3,Sub-Saharan Africa,Democratic Republic of the Congo,Online,7683,502.54,668.27
4,Europe,Czech Republic,Online,3491,31.79,47.45
...,...,...,...,...,...,...
9995,Asia,Laos,Online,8597,31.79,47.45
9996,Europe,Liechtenstein,Online,562,263.33,437.20
9997,Sub-Saharan Africa,Democratic Republic of the Congo,Offline,2524,90.93,154.06
9998,Sub-Saharan Africa,South Africa,Online,8706,364.69,421.89
9999,Asia,Mongolia,Offline,361,97.44,152.58

# 데이터의 결합
1. Union 결합 (데이터 간의 단순한 결합)
    - 단순하게 행을 결합하거나 열을 결합하는 방법
    - sql에서는
        - table UNION table2
    - pandas에서는
        - concat([df, df2], axis={0|1})  #일반적으로 concat은 행으로 결합함.
2. Join 결합 (특정한 조건의 맞춰서 열을 결합)
    - 특정한 컬럼의 데이터를 기준으로 하여 해당하는 값들이 일치한다면 열을 결합해줌.
    - sql
        - table join table2 on 조건식
    - pandas
        - merge(df, df2, on = 조건식, how = 결합방식)  #단순했던 concat과는 달리 변수 2개 df, df2가 끝임. 그 초과는 한번에 못함

In [50]:
sql = """
    SELECT
    *
    FROM
    tran_1
"""
cursor.execute(sql)
data1 = cursor.fetchall()
df = pd.DataFrame(data1)
df

     transaction_id   price         payment_date customer_id
0       T0000000113  210000  2019-02-01 01:36:57    PL563502
1       T0000000114   50000  2019-02-01 01:37:23    HD678019
2       T0000000115  120000  2019-02-01 02:34:19    HD298120
3       T0000000116  210000  2019-02-01 02:47:23    IK452215
4       T0000000117  170000  2019-02-01 04:33:46    PL542865
...             ...     ...                  ...         ...
4995    T0000005108  210000  2019-06-15 02:42:41    HD315748
4996    T0000005109  150000  2019-06-15 03:36:16    HI215420
4997    T0000005110   50000  2019-06-15 03:44:06    IK880102
4998    T0000005111  210000  2019-06-15 04:14:06    IK074758
4999    T0000005112   50000  2019-06-15 04:42:38    HD444151

[5000 rows x 4 columns]

In [51]:
sql = """
    SELECT
    *
    FROM tran_2
"""
cursor.execute(sql)
data2 = cursor.fetchall()
df2 = pd.DataFrame(data2)
df2

     transaction_id   price         payment_date customer_id
0       T0000005113  295000  2019-06-15 07:20:27    TS169261
1       T0000005114   50000  2019-06-15 07:35:47    HI599892
2       T0000005115   85000  2019-06-15 07:56:36    HI421757
3       T0000005116   50000  2019-06-15 08:40:55    OA386378
4       T0000005117  120000  2019-06-15 08:44:23    TS506913
...             ...     ...                  ...         ...
1781    T0000006894  180000  2019-07-31 21:20:44    HI400734
1782    T0000006895   85000  2019-07-31 21:52:48    AS339451
1783    T0000006896  100000  2019-07-31 23:35:25    OA027325
1784    T0000006897   85000  2019-07-31 23:39:35    TS624738
1785    T0000006898   85000  2019-07-31 23:41:38    AS834214

[1786 rows x 4 columns]

In [52]:
# sql 쿼리문을 이용하여 데이터를 단순 행 결합
sql = """
    select * from tran_1
    union
    select * from tran_2;
"""
cursor.execute(sql)
data3 = cursor.fetchall()
df3 = pd.DataFrame(data3)
df3

     transaction_id   price         payment_date customer_id
0       T0000000113  210000  2019-02-01 01:36:57    PL563502
1       T0000000114   50000  2019-02-01 01:37:23    HD678019
2       T0000000115  120000  2019-02-01 02:34:19    HD298120
3       T0000000116  210000  2019-02-01 02:47:23    IK452215
4       T0000000117  170000  2019-02-01 04:33:46    PL542865
...             ...     ...                  ...         ...
6781    T0000006894  180000  2019-07-31 21:20:44    HI400734
6782    T0000006895   85000  2019-07-31 21:52:48    AS339451
6783    T0000006896  100000  2019-07-31 23:35:25    OA027325
6784    T0000006897   85000  2019-07-31 23:39:35    TS624738
6785    T0000006898   85000  2019-07-31 23:41:38    AS834214

[6786 rows x 4 columns]

In [53]:
# pandas를 이용하여 데이터프레임을 단순 행 결합
# pd.concat([df, df2], axis=0)
# 근데 concat으로 하면 인덱스도 그대로 걍 붙임
pd.concat([df, df2], axis=0, ignore_index=True) #ignore_index=True하면 인덱스 초기화됨.

     transaction_id   price         payment_date customer_id
0       T0000000113  210000  2019-02-01 01:36:57    PL563502
1       T0000000114   50000  2019-02-01 01:37:23    HD678019
2       T0000000115  120000  2019-02-01 02:34:19    HD298120
3       T0000000116  210000  2019-02-01 02:47:23    IK452215
4       T0000000117  170000  2019-02-01 04:33:46    PL542865
...             ...     ...                  ...         ...
6781    T0000006894  180000  2019-07-31 21:20:44    HI400734
6782    T0000006895   85000  2019-07-31 21:52:48    AS339451
6783    T0000006896  100000  2019-07-31 23:35:25    OA027325
6784    T0000006897   85000  2019-07-31 23:39:35    TS624738
6785    T0000006898   85000  2019-07-31 23:41:38    AS834214

[6786 rows x 4 columns]

In [54]:
# 인자값으로 쿼리문을 입력하면 결과를 데이터프레임으로 되돌려주는 함수를 만들어보자(좀 더 편하게 살자).
def sql_load(sql):
    cursor.execute(sql)
    data = cursor.fetchall()
    result = pd.DataFrame(data)
    return result

In [55]:
sql = """
    select
    *
    from
    emp
"""
emp = sql_load(sql)
emp

   EMPNO   ENAME        JOB   MGR    HIREDATE      SAL     COMM DEPTNO
0   7369   SMITH      CLERK  7902  1980-12-17   800.00     None     20
1   7499   ALLEN   SALESMAN  7698  1981-02-20  1600.00   300.00     30
2   7521    WARD   SALESMAN  7698  1981-02-22  1250.00   500.00     30
3   7566   JONES    MANAGER  7839  1981-04-02  2975.00     None     20
4   7654  MARTIN   SALESMAN  7698  1981-09-28  1250.00  1400.00     30
5   7698   BLAKE    MANAGER  7839  1981-05-01  2850.00     None     30
6   7782   CLARK    MANAGER  7839  1981-06-09  2450.00     None     10
7   7788   SCOTT    ANALYST  7566  1987-06-28  3000.00     None     20
8   7839    KING  PRESIDENT  None  1981-11-17  5000.00     None     10
9   7844  TURNER   SALESMAN  7698  1981-09-08  1500.00     0.00     30
10  7876   ADAMS      CLERK  7788  1987-07-13  1100.00     None     20
11  7900   JAMES      CLERK  7698  1981-12-03   950.00     None     30
12  7902    FORD    ANALYST  7566  1981-12-03  3000.00     None     20
13  7934  MILLER      CLERK  7782  1982-01-23  1300.00     None     10

In [56]:
sql = """
    select
    *
    from
    dept
"""
dept = sql_load(sql)
dept

  DEPTNO       DNAME       LOC
0     10  ACCOUNTING  NEW YORK
1     20    RESEARCH    DALLAS
2     30       SALES   CHICAGO
3     40  OPERATIONS    BOSTON
4     50         CEO  NEW YORK

In [57]:
# join 결합 sql
sql = """
    select
    *
    from
    emp
    left join  #left(여기서 왼쪽은 줄바꿈 전의 왼쪽이니까 emp)를 기준으로 join을 하겠다. 
    dept
    on
    emp.DEPTNO = dept.DEPTNO
"""
sql_load(sql)

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,dept.DEPTNO,DNAME,LOC
0,7369,SMITH,CLERK,7902,1980-12-17,800.00,None,20,20,RESEARCH,DALLAS
1,7499,ALLEN,SALESMAN,7698,1981-02-20,1600.00,300.00,30,30,SALES,CHICAGO
2,7521,WARD,SALESMAN,7698,1981-02-22,1250.00,500.00,30,30,SALES,CHICAGO
3,7566,JONES,MANAGER,7839,1981-04-02,2975.00,None,20,20,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698,1981-09-28,1250.00,1400.00,30,30,SALES,CHICAGO
5,7698,BLAKE,MANAGER,7839,1981-05-01,2850.00,None,30,30,SALES,CHICAGO
6,7782,CLARK,MANAGER,7839,1981-06-09,2450.00,None,10,10,ACCOUNTING,NEW YORK
7,7788,SCOTT,ANALYST,7566,1987-06-28,3000.00,None,20,20,RESEARCH,DALLAS
8,7839,KING,PRESIDENT,None,1981-11-17,5000.00,None,10,10,ACCOUNTING,NEW YORK
9,7844,TURNER,SALESMAN,7698,1981-09-08,1500.00,0.00,30,30,SALES,CHICAGO
10,7876,ADAMS,CLERK,7788,1987-07-13,1100.00,None,20,20,RESEARCH,DALLAS
11,7900,JAMES,CLERK,7698,1981-12-03,950.00,None,30,30,SALES,CHICAGO
12,7902,FORD,ANALYST,7566,1981-12-03,3000.00,None,20,20,RESEARCH,DALLAS
13,7934,MILLER,CLERK,7782,1982-01-23,1300.00,None,10,10,ACCOUNTING,NEW YORK

In [58]:
# pandas를 이용하여 join 결합을 해보자 (merge)
pd.merge(emp, dept, on = 'DEPTNO', how = 'left')
# sql의 join과 다른점은 pandas에서는 DEPTNO가 같으므로 한번만 보여줌.

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC
0,7369,SMITH,CLERK,7902,1980-12-17,800.00,None,20,RESEARCH,DALLAS
1,7499,ALLEN,SALESMAN,7698,1981-02-20,1600.00,300.00,30,SALES,CHICAGO
2,7521,WARD,SALESMAN,7698,1981-02-22,1250.00,500.00,30,SALES,CHICAGO
3,7566,JONES,MANAGER,7839,1981-04-02,2975.00,None,20,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698,1981-09-28,1250.00,1400.00,30,SALES,CHICAGO
5,7698,BLAKE,MANAGER,7839,1981-05-01,2850.00,None,30,SALES,CHICAGO
6,7782,CLARK,MANAGER,7839,1981-06-09,2450.00,None,10,ACCOUNTING,NEW YORK
7,7788,SCOTT,ANALYST,7566,1987-06-28,3000.00,None,20,RESEARCH,DALLAS
8,7839,KING,PRESIDENT,None,1981-11-17,5000.00,None,10,ACCOUNTING,NEW YORK
9,7844,TURNER,SALESMAN,7698,1981-09-08,1500.00,0.00,30,SALES,CHICAGO
10,7876,ADAMS,CLERK,7788,1987-07-13,1100.00,None,20,RESEARCH,DALLAS
11,7900,JAMES,CLERK,7698,1981-12-03,950.00,None,30,SALES,CHICAGO
12,7902,FORD,ANALYST,7566,1981-12-03,3000.00,None,20,RESEARCH,DALLAS
13,7934,MILLER,CLERK,7782,1982-01-23,1300.00,None,10,ACCOUNTING,NEW YORK

In [59]:
# pandas를 이용하여 join 결합을 해보자 (merge)
pd.merge(emp, dept, on = 'DEPTNO', how = 'right') #right도 해볼까염

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC
0,7782,CLARK,MANAGER,7839,1981-06-09,2450.00,None,10,ACCOUNTING,NEW YORK
1,7839,KING,PRESIDENT,None,1981-11-17,5000.00,None,10,ACCOUNTING,NEW YORK
2,7934,MILLER,CLERK,7782,1982-01-23,1300.00,None,10,ACCOUNTING,NEW YORK
3,7369,SMITH,CLERK,7902,1980-12-17,800.00,None,20,RESEARCH,DALLAS
4,7566,JONES,MANAGER,7839,1981-04-02,2975.00,None,20,RESEARCH,DALLAS
5,7788,SCOTT,ANALYST,7566,1987-06-28,3000.00,None,20,RESEARCH,DALLAS
6,7876,ADAMS,CLERK,7788,1987-07-13,1100.00,None,20,RESEARCH,DALLAS
7,7902,FORD,ANALYST,7566,1981-12-03,3000.00,None,20,RESEARCH,DALLAS
8,7499,ALLEN,SALESMAN,7698,1981-02-20,1600.00,300.00,30,SALES,CHICAGO
9,7521,WARD,SALESMAN,7698,1981-02-22,1250.00,500.00,30,SALES,CHICAGO
10,7654,MARTIN,SALESMAN,7698,1981-09-28,1250.00,1400.00,30,SALES,CHICAGO
11,7698,BLAKE,MANAGER,7839,1981-05-01,2850.00,None,30,SALES,CHICAGO
12,7844,TURNER,SALESMAN,7698,1981-09-08,1500.00,0.00,30,SALES,CHICAGO
13,7900,JAMES,CLERK,7698,1981-12-03,950.00,None,30,SALES,CHICAGO
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40,OPERATIONS,BOSTON
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50,CEO,NEW YORK

In [70]:
class Mysql:
    # 생성자 함수 : class가 생성될 때 최초로 한번만 실행이 되는 함수를 의미한다. 초기화 함수라고도 부름.
    def __init__(self, _host, _user, _pass, _db, _port):
        self.host = _host
        self.user = _user
        self.password = _pass
        self.db = _db
        self.port = _port
        
    # sql 쿼리문을 입력값으로 받아서 쿼리문을 실행하고 결과값을 되돌려주는 함수
    def sql_load(self, _sql, _value = []):
        # 데이터베이스 서버와의 연결
        _db = pymysql.connect(
            host = self.host,
            user = self.user,
            password = self.password,
            database = self.db,
            port = self.port
        )
        # Cursor 생성
        cursor = _db.cursor(pymysql.cursors.DictCursor)
        
        # sql 쿼리문을 실행
        cursor.execute(_sql,_value)
        
        # _sql 시작이 select로 시작하는 경우
        if _sql.strip().lower().startswith('select'):
            result = cursor.fetchall()
        # 아닌경우
        else:
            _db.commit()
            result = 'Query OK'
            
        # 데이터베이스와의 연결을 종료
        _db.close()
        
        return result

In [69]:
sql = """
    select
    *
    from
    emp
"""
# sql.strip().lower()[0:6] == 'select' #누군가는 쿼리문을 대문자로 쓸 수도 있으니까.
sql.strip().lower().startswith('select') #귀찮으니까 이런 함수가 있다~

True